version: "3"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "81:80"
    depends_on:
      - conversation

  chatui:
    build: ./chatui

  conversation:
    build: ./conversation
#    ports:
#      - "82:80"
    environment:
      - AGENT_ENDPOINT=http://nginx:80/assistant
    depends_on:
      - redis

  assistant:
    build: ./assistant
#    ports:
#      - "83:80"
    env_file:
      - .env
    depends_on:
        - conversation

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data

volumes:
  redis_data:
